### PR TITLE
fix: Fix deadlock/transaction issues with expose clientID on Read/WriteTransaction

### LINKED ISSUE #541: RFE: Expose clientID on Read/WriteTransaction
Many mutators in multiplayer apps end up taking the clientID as a parameter. It would be nice if it was implicitly available.

This would also allow for a nice symmetry with the subscription functions, which can already be written to rely on the clientID implicitly, because they only run on client side and can therefore grab it out of some other state.

### PR DESCRIPTION
**Pull request by grgbkr**
This change

1. Addresses arv's feedback on PR #613
2. Fixes issue where awaiting clientID inside a dag transaction was causing deadlocks and/or prematurely closing idb transactions.
3. Restructures `Replicache#_open` to avoid unnecessarily delaying the resolution of _clientIDPromise (currently blocks on db initialization and `this._getRoot`).

Closes #541

### CODE REVIEW

File: src/replicache.ts [hunk 1]
```diff
@@ -333,9 +337,10 @@ export class Replicache<MD extends MutatorDefs = {}> {
       sync.initClientID(this._kvStore),
       db.maybeInitDefaultDB(this._dagStore),
     ]);
+    resolveClientID(clientID);
 
     // Now we have both a clientID and DB!
-    this._resolveReady();
+    resolveReady();
```
Comment (arv) [inline src/replicache.ts:344]: We might be able to only use one resolver now

File: src/replicache.ts [hunk 2]
```diff
@@ -573,13 +577,14 @@ export class Replicache<MD extends MutatorDefs = {}> {
     f: (tx: IndexTransactionImpl) => Promise<void>,
   ): Promise<void> {
     await this._ready;
+    // clientID must be awaited ouside dag transaction to avoid a premature
```
Comment (grgbkr) [inline src/replicache.ts:581]: @arv do you think these comments are useful?

**Comment by arv** [comment]
LGTM

File: src/replicache.ts (hunk 2 above)
Comment (arv) [reply src/replicache.ts:581]: yes

Comment (arv) [reply src/replicache.ts:581]: but if we make _ready and clientID promise the same promise this would be clearer maybe?

File: src/replicache.ts (hunk 1 above)
Comment (grgbkr) [reply src/replicache.ts:344]: the ready bit is still used in a bunch of places where clientID is not at the moment, so its not straightforward to get rid of ready.

Comment (grgbkr) [reply src/replicache.ts:344]: i also made another small change that avoids blocking resolution of the clientIdPromise on the db initialization

**Comment by aboodman** [comment]
Nice!

**Comment by aboodman** [comment]
I can't see exactly what went wrong here with the perf test, but I can replicate it locally so I'm going to revert, sorry!
